version: '3'

services:
  backend:
    image: registry.gitlab.propulsion-home.ch/full-stack/batch-15-february-2021/final-projects/djone:latest
    restart: always
    env_file:
      - ./envs/dev.env
    command: 'sh /scripts/dev.sh'
    volumes:
      - ./backend:/backend
      - media-files:/media-files
      - static-files:/static-files
    ports:
      - '8000:8000'
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    ports:
      - '5432:5432'

    # these volumes pass the data from your computer to the docker container
    volumes:
      - postgres:/var/lib/postgresql/data
    env_file:
      - ./envs/dev.env

# this volume create directory in your computer so that if no matter what happens to the container the data will not be delete
volumes:
  postgres:
  media-files:
  static-files:
