# Generated by Django 3.1 on 2021-04-15 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('measurements', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoltageProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(blank=True, max_length=20, verbose_name='Direction')),
                ('distanz', models.CharField(blank=True, max_length=20, verbose_name='Distance1')),
                ('hier', models.CharField(blank=True, max_length=20, verbose_name='here1')),
                ('spannung', models.CharField(blank=True, max_length=20, verbose_name='Voltage1')),
                ('bemerkung', models.CharField(blank=True, max_length=1200, verbose_name='Comment')),
                ('distanz1', models.CharField(blank=True, max_length=20, verbose_name='Distance1')),
                ('hier1', models.CharField(blank=True, max_length=20, verbose_name='Here')),
                ('spannung1', models.CharField(blank=True, max_length=20, verbose_name='Voltage')),
                ('bemerkung1', models.CharField(blank=True, max_length=1200, verbose_name='Comment')),
                ('distanz2', models.CharField(blank=True, max_length=20, verbose_name='Distance2')),
                ('hier2', models.CharField(blank=True, max_length=20, verbose_name='Here')),
                ('spannung2', models.CharField(blank=True, max_length=20, verbose_name='Voltage')),
                ('bemerkung2', models.CharField(blank=True, max_length=1200, verbose_name='Comment')),
                ('distanz3', models.CharField(blank=True, max_length=20, verbose_name='Distance3')),
                ('hier3', models.CharField(blank=True, max_length=20, verbose_name='Here')),
                ('spannung3', models.CharField(blank=True, max_length=20, verbose_name='Voltage')),
                ('bemerkung3', models.CharField(blank=True, max_length=1200, verbose_name='Comment')),
                ('distanz4', models.CharField(blank=True, max_length=20, verbose_name='Distance4')),
                ('hier4', models.CharField(blank=True, max_length=20, verbose_name='Here')),
                ('spannung4', models.CharField(blank=True, max_length=20, verbose_name='Voltage')),
                ('bemerkung4', models.CharField(blank=True, max_length=1200, verbose_name='Comment')),
                ('distanz5', models.CharField(blank=True, max_length=20, verbose_name='Distance5')),
                ('hier5', models.CharField(blank=True, max_length=20, verbose_name='Here')),
                ('spannung5', models.CharField(blank=True, max_length=20, verbose_name='Voltage')),
                ('bemerkung5', models.CharField(blank=True, max_length=1200, verbose_name='Comment')),
                ('date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='date')),
                ('measurement', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voltage_profile', to='measurements.measurements')),
            ],
        ),
    ]
