# Generated by Django 3.1 on 2021-04-15 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voltage_profile', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voltageprofile',
            name='hier',
        ),
        migrations.RemoveField(
            model_name='voltageprofile',
            name='hier1',
        ),
        migrations.RemoveField(
            model_name='voltageprofile',
            name='hier2',
        ),
        migrations.RemoveField(
            model_name='voltageprofile',
            name='hier3',
        ),
        migrations.RemoveField(
            model_name='voltageprofile',
            name='hier4',
        ),
        migrations.RemoveField(
            model_name='voltageprofile',
            name='hier5',
        ),
    ]
