# Generated by Django 3.1 on 2021-04-18 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voltage_profile', '0002_auto_20210415_1858'),
    ]

    operations = [
        migrations.AddField(
            model_name='voltageprofile',
            name='bemerkung10',
            field=models.CharField(blank=True, max_length=1200, verbose_name='Comment'),
        ),
        migrations.AddField(
            model_name='voltageprofile',
            name='bemerkung12',
            field=models.CharField(blank=True, max_length=1200, verbose_name='Comment'),
        ),
        migrations.AddField(
            model_name='voltageprofile',
            name='bemerkung13',
            field=models.CharField(blank=True, max_length=1200, verbose_name='Comment'),
        ),
        migrations.AddField(
            model_name='voltageprofile',
            name='bemerkung14',
            field=models.CharField(blank=True, max_length=1200, verbose_name='Comment'),
        ),
        migrations.AddField(
            model_name='voltageprofile',
            name='bemerkung15',
            field=models.CharField(blank=True, max_length=1200, verbose_name='Comment'),
        ),
        migrations.AddField(
            model_name='voltageprofile',
            name='bemerkung16',
            field=models.CharField(blank=True, max_length=1200, verbose_name='Comment'),
        ),
        migrations.AddField(
            model_name='voltageprofile',
            name='bemerkung17',
            field=models.CharField(blank=True, max_length=1200, verbose_name='Comment'),
        ),
        migrations.AddField(
            model_name='voltageprofile',
            name='bemerkung18',
            field=models.CharField(blank=True, max_length=1200, verbose_name='Comment'),
        ),
        migrations.AddField(
            model_name='voltageprofile',
            name='bemerkung19',
            field=models.CharField(blank=True, max_length=1200, verbose_name='Comment'),
        ),
        migrations.AddField(
            model_name='voltageprofile',
            name='bemerkung20',
            field=models.CharField(blank=True, max_length=1200, verbose_name='Comment'),
        ),
        migrations.AddField(
            model_name='voltageprofile',
            name='bemerkung21',
            field=models.CharField(blank=True, max_length=1200, verbose_name='Comment'),
        ),
        migrations.AddField(
            model_name='voltageprofile',
            name='bemerkung22',
            field=models.CharField(blank=True, max_length=1200, verbose_name='Comment'),
        ),
        migrations.AddField(
            model_name='voltageprofile',
            name='bemerkung23',
            field=models.CharField(blank=True, max_length=1200, verbose_name='Comment'),
        ),
        migrations.AddField(
            model_name='voltageprofile',
            name='bemerkung24',
            field=models.CharField(blank=True, max_length=1200, verbose_name='Comment'),
        ),
        migrations.AddField(
            model_name='voltageprofile',
            name='bemerkung25',
            field=models.CharField(blank=True, max_length=1200, verbose_name='Comment'),
        ),
        migrations.AddField(
            model_name='voltageprofile',
            name='bemerkung26',
            field=models.CharField(blank=True, max_length=1200, verbose_name='Comment'),
        ),
        migrations.AddField(
            model_name='voltageprofile',
            name='bemerkung27',
            field=models.CharField(blank=True, max_length=1200, verbose_name='Comment'),
        ),
        migrations.AddField(
            model_name='voltageprofile',
            name='bemerkung28',
            field=models.CharField(blank=True, max_length=1200, verbose_name='Comment'),
        ),
        migrations.AddField(
            model_name='voltageprofile',
            name='bemerkung29',
            field=models.CharField(blank=True, max_length=1200, verbose_name='Comment'),
        ),
        migrations.AddField(
            model_name='voltageprofile',
            name='bemerkung30',
            field=models.CharField(blank=True, max_length=1200, verbose_name='Comment'),
        ),
        migrations.AddField(
            model_name='voltageprofile',
            name='bemerkung6',
            field=models.CharField(blank=True, max_length=1200, verbose_name='Comment'),
        ),
        migrations.AddField(
            model_name='voltageprofile',
            name='bemerkung7',
            field=models.CharField(blank=True, max_length=1200, verbose_name='Comment'),
        ),
        migrations.AddField(
            model_name='voltageprofile',
            name='bemerkung8',
            field=models.CharField(blank=True, max_length=1200, verbose_name='Comment'),
        ),
        migrations.AddField(
            model_name='voltageprofile',
            name='bemerkung9',
            field=models.CharField(blank=True, max_length=1200, verbose_name='Comment'),
        ),
        migrations.AddField(
            model_name='voltageprofile',
            name='distanz10',
            field=models.CharField(blank=True, max_length=20, verbose_name='Distance10'),
        ),
        migrations.AddField(
            model_name='voltageprofile',
            name='distanz12',
            field=models.CharField(blank=True, max_length=20, verbose_name='Distance12'),
        ),
        migrations.AddField(
            model_name='voltageprofile',
            name='distanz13',
            field=models.CharField(blank=True, max_length=20, verbose_name='Distance13'),
        ),
        migrations.AddField(
            model_name='voltageprofile',
            name='distanz14',
            field=models.CharField(blank=True, max_length=20, verbose_name='Distance14'),
        ),
        migrations.AddField(
            model_name='voltageprofile',
            name='distanz15',
            field=models.CharField(blank=True, max_length=20, verbose_name='Distance15'),
        ),
        migrations.AddField(
            model_name='voltageprofile',
            name='distanz16',
            field=models.CharField(blank=True, max_length=20, verbose_name='Distance16'),
        ),
        migrations.AddField(
            model_name='voltageprofile',
            name='distanz17',
            field=models.CharField(blank=True, max_length=20, verbose_name='Distance17'),
        ),
        migrations.AddField(
            model_name='voltageprofile',
            name='distanz18',
            field=models.CharField(blank=True, max_length=20, verbose_name='Distance18'),
        ),
        migrations.AddField(
            model_name='voltageprofile',
            name='distanz19',
            field=models.CharField(blank=True, max_length=20, verbose_name='Distance19'),
        ),
        migrations.AddField(
            model_name='voltageprofile',
            name='distanz20',
            field=models.CharField(blank=True, max_length=20, verbose_name='Distance20'),
        ),
        migrations.AddField(
            model_name='voltageprofile',
            name='distanz21',
            field=models.CharField(blank=True, max_length=20, verbose_name='Distance21'),
        ),
        migrations.AddField(
            model_name='voltageprofile',
            name='distanz22',
            field=models.CharField(blank=True, max_length=20, verbose_name='Distance22'),
        ),
        migrations.AddField(
            model_name='voltageprofile',
            name='distanz23',
            field=models.CharField(blank=True, max_length=20, verbose_name='Distance23'),
        ),
        migrations.AddField(
            model_name='voltageprofile',
            name='distanz24',
            field=models.CharField(blank=True, max_length=20, verbose_name='Distance24'),
        ),
        migrations.AddField(
            model_name='voltageprofile',
            name='distanz25',
            field=models.CharField(blank=True, max_length=20, verbose_name='Distance25'),
        ),
        migrations.AddField(
            model_name='voltageprofile',
            name='distanz26',
            field=models.CharField(blank=True, max_length=20, verbose_name='Distance26'),
        ),
        migrations.AddField(
            model_name='voltageprofile',
            name='distanz27',
            field=models.CharField(blank=True, max_length=20, verbose_name='Distance27'),
        ),
        migrations.AddField(
            model_name='voltageprofile',
            name='distanz28',
            field=models.CharField(blank=True, max_length=20, verbose_name='Distance28'),
        ),
        migrations.AddField(
            model_name='voltageprofile',
            name='distanz29',
            field=models.CharField(blank=True, max_length=20, verbose_name='Distance29'),
        ),
        migrations.AddField(
            model_name='voltageprofile',
            name='distanz30',
            field=models.CharField(blank=True, max_length=20, verbose_name='Distance30'),
        ),
        migrations.AddField(
            model_name='voltageprofile',
            name='distanz6',
            field=models.CharField(blank=True, max_length=20, verbose_name='Distance6'),
        ),
        migrations.AddField(
            model_name='voltageprofile',
            name='distanz7',
            field=models.CharField(blank=True, max_length=20, verbose_name='Distance7'),
        ),
        migrations.AddField(
            model_name='voltageprofile',
            name='distanz8',
            field=models.CharField(blank=True, max_length=20, verbose_name='Distance8'),
        ),
        migrations.AddField(
            model_name='voltageprofile',
            name='distanz9',
            field=models.CharField(blank=True, max_length=20, verbose_name='Distance9'),
        ),
        migrations.AddField(
            model_name='voltageprofile',
            name='spannung10',
            field=models.CharField(blank=True, max_length=20, verbose_name='Voltage'),
        ),
        migrations.AddField(
            model_name='voltageprofile',
            name='spannung12',
            field=models.CharField(blank=True, max_length=20, verbose_name='Voltage'),
        ),
        migrations.AddField(
            model_name='voltageprofile',
            name='spannung13',
            field=models.CharField(blank=True, max_length=20, verbose_name='Voltage'),
        ),
        migrations.AddField(
            model_name='voltageprofile',
            name='spannung14',
            field=models.CharField(blank=True, max_length=20, verbose_name='Voltage'),
        ),
        migrations.AddField(
            model_name='voltageprofile',
            name='spannung15',
            field=models.CharField(blank=True, max_length=20, verbose_name='Voltage'),
        ),
        migrations.AddField(
            model_name='voltageprofile',
            name='spannung16',
            field=models.CharField(blank=True, max_length=20, verbose_name='Voltage'),
        ),
        migrations.AddField(
            model_name='voltageprofile',
            name='spannung17',
            field=models.CharField(blank=True, max_length=20, verbose_name='Voltage'),
        ),
        migrations.AddField(
            model_name='voltageprofile',
            name='spannung18',
            field=models.CharField(blank=True, max_length=20, verbose_name='Voltage'),
        ),
        migrations.AddField(
            model_name='voltageprofile',
            name='spannung19',
            field=models.CharField(blank=True, max_length=20, verbose_name='Voltage'),
        ),
        migrations.AddField(
            model_name='voltageprofile',
            name='spannung20',
            field=models.CharField(blank=True, max_length=20, verbose_name='Voltage'),
        ),
        migrations.AddField(
            model_name='voltageprofile',
            name='spannung21',
            field=models.CharField(blank=True, max_length=20, verbose_name='Voltage'),
        ),
        migrations.AddField(
            model_name='voltageprofile',
            name='spannung22',
            field=models.CharField(blank=True, max_length=20, verbose_name='Voltage'),
        ),
        migrations.AddField(
            model_name='voltageprofile',
            name='spannung23',
            field=models.CharField(blank=True, max_length=20, verbose_name='Voltage'),
        ),
        migrations.AddField(
            model_name='voltageprofile',
            name='spannung24',
            field=models.CharField(blank=True, max_length=20, verbose_name='Voltage'),
        ),
        migrations.AddField(
            model_name='voltageprofile',
            name='spannung25',
            field=models.CharField(blank=True, max_length=20, verbose_name='Voltage'),
        ),
        migrations.AddField(
            model_name='voltageprofile',
            name='spannung26',
            field=models.CharField(blank=True, max_length=20, verbose_name='Voltage'),
        ),
        migrations.AddField(
            model_name='voltageprofile',
            name='spannung27',
            field=models.CharField(blank=True, max_length=20, verbose_name='Voltage'),
        ),
        migrations.AddField(
            model_name='voltageprofile',
            name='spannung28',
            field=models.CharField(blank=True, max_length=20, verbose_name='Voltage'),
        ),
        migrations.AddField(
            model_name='voltageprofile',
            name='spannung29',
            field=models.CharField(blank=True, max_length=20, verbose_name='Voltage'),
        ),
        migrations.AddField(
            model_name='voltageprofile',
            name='spannung30',
            field=models.CharField(blank=True, max_length=20, verbose_name='Voltage'),
        ),
        migrations.AddField(
            model_name='voltageprofile',
            name='spannung6',
            field=models.CharField(blank=True, max_length=20, verbose_name='Voltage'),
        ),
        migrations.AddField(
            model_name='voltageprofile',
            name='spannung7',
            field=models.CharField(blank=True, max_length=20, verbose_name='Voltage'),
        ),
        migrations.AddField(
            model_name='voltageprofile',
            name='spannung8',
            field=models.CharField(blank=True, max_length=20, verbose_name='Voltage'),
        ),
        migrations.AddField(
            model_name='voltageprofile',
            name='spannung9',
            field=models.CharField(blank=True, max_length=20, verbose_name='Voltage'),
        ),
    ]
