# Generated by Django 3.1 on 2021-04-21 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voltage_profile', '0003_auto_20210418_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='voltageprofile',
            name='project_identifier',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
