# Generated by Django 3.1 on 2021-04-15 14:39

from django.db import migrations, models
import django.db.models.deletion
import touch_voltage.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('measurements', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TouchVoltage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bezeichnung', models.CharField(blank=True, max_length=1200, verbose_name='description')),
                ('kategorie', models.CharField(choices=[('0', 'Please choose a category'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G'), ('H', 'H'), ('I', 'I'), ('J', 'J'), ('K', 'K'), ('L', 'L'), ('M', 'M'), ('N', 'N'), ('O', 'O'), ('P', 'P'), ('Q', 'Q'), ('R', 'R'), ('S', 'S'), ('T', 'T'), ('U', 'U'), ('V', 'V'), ('W', 'W'), ('X', 'X'), ('Y', 'Y'), ('Z', 'Z')], default='0', max_length=1, verbose_name='category')),
                ('beruhrungsspannung_high_Z', models.CharField(blank=True, max_length=20, verbose_name='touch_voltage_high_Z')),
                ('beruhrungsspannung_low_Z', models.CharField(blank=True, max_length=200, verbose_name='touch_voltage_low_Z')),
                ('kommentar', models.CharField(blank=True, max_length=1200, verbose_name='comment')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='date')),
                ('foto', models.ImageField(blank=True, upload_to=touch_voltage.models.user_directory_path, verbose_name='Add photo')),
                ('spannungsdiff_low_Z', models.CharField(blank=True, max_length=20)),
                ('spannungsdiff_high_Z', models.CharField(blank=True, max_length=20)),
                ('measurement', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='touch_voltage', to='measurements.measurements')),
            ],
        ),
    ]
