# Generated by Django 3.1 on 2021-04-19 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('measurements', '0004_auto_20210418_1723'),
        ('touch_voltage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='touchvoltage',
            name='frontend_id',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='touchvoltage',
            name='geometry_x',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='touchvoltage',
            name='geometry_y',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='touchvoltage',
            name='measurement',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='touch_voltage_annotation', to='measurements.measurements'),
        ),
    ]
