# Generated by Django 3.1 on 2021-04-19 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
        ('touch_voltage', '0002_auto_20210419_1119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='touchvoltage',
            name='measurement',
        ),
        migrations.AddField(
            model_name='touchvoltage',
            name='map',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='touch_voltage_annotation_map', to='map.map'),
        ),
    ]
