# Generated by Django 3.1 on 2021-04-21 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('touch_voltage', '0004_touchvoltage_project_identifier'),
    ]

    operations = [
        migrations.AddField(
            model_name='touchvoltage',
            name='map_name',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
