# Generated by Django 3.1 on 2021-04-22 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('touch_voltage', '0005_touchvoltage_map_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='touchvoltage',
            name='kategorie',
            field=models.CharField(max_length=2, verbose_name='category'),
        ),
    ]
