# Generated by Django 3.1 on 2021-04-15 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Measurements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.CharField(blank=True, max_length=200)),
                ('site', models.CharField(blank=True, max_length=200, verbose_name='Plant/Equipment')),
                ('used_power_line', models.CharField(blank=True, max_length=200, verbose_name='cable used')),
                ('date', models.DateField(blank=True, null=True, verbose_name='date basic data')),
                ('updated_form_date', models.DateTimeField(auto_now=True)),
                ('fault_current', models.CharField(blank=True, max_length=200)),
                ('clearing_time', models.CharField(blank=True, max_length=200)),
                ('touch_voltage_allowed', models.CharField(blank=True, max_length=200)),
                ('scaling_factor', models.CharField(blank=True, max_length=200)),
                ('scaled_touch_voltage_allowed', models.CharField(blank=True, max_length=200)),
                ('measuring_current', models.CharField(blank=True, max_length=200)),
                ('additional_info_attributes', models.CharField(blank=True, max_length=20)),
                ('measurement_values', models.CharField(blank=True, max_length=20)),
                ('location_on_map', models.CharField(blank=True, max_length=20)),
                ('firma', models.CharField(blank=True, max_length=20, verbose_name='Client')),
                ('anlage', models.CharField(blank=True, max_length=20, verbose_name='Plant / Equipment')),
                ('benutzte_leitung', models.CharField(blank=True, max_length=200, verbose_name='Cable Used')),
                ('datum_auto_add', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('erdschluss_storm', models.CharField(blank=True, max_length=20, verbose_name='Earth Fault Current')),
                ('fehlerklaerungszeit', models.CharField(blank=True, max_length=20, verbose_name='Error Resolving Time')),
                ('erlaubte_beruhrungsspannung', models.CharField(blank=True, max_length=20, verbose_name='Allowed Touch Voltage')),
                ('mess_strom', models.CharField(blank=True, max_length=20, verbose_name='Measuring Current')),
                ('skalierungsfaktor', models.CharField(blank=True, max_length=20, verbose_name='Scaling Factor')),
                ('erlaubte_beruhrungsspannung_skaliert', models.CharField(blank=True, max_length=20, verbose_name='Allowed Touch Voltage scaled')),
                ('primaestrom', models.CharField(blank=True, max_length=20, verbose_name='first storm')),
                ('messstrom', models.CharField(blank=True, max_length=20, verbose_name='Measuring Current-Messparameter')),
                ('schleifenspannung', models.CharField(blank=True, max_length=200, verbose_name='schleifenspannung')),
                ('temperature', models.CharField(blank=True, max_length=20)),
                ('wetter', models.CharField(blank=True, max_length=200, verbose_name='weather')),
                ('Bodenfeuchte', models.CharField(blank=True, max_length=20)),
                ('leitung1', models.CharField(blank=True, max_length=20, verbose_name='Cables1')),
                ('strom_A_1', models.CharField(blank=True, max_length=20, verbose_name='Current1')),
                ('leitung2', models.CharField(blank=True, max_length=20, verbose_name='Cables2')),
                ('strom_A_2', models.CharField(blank=True, max_length=20, verbose_name='Current1')),
                ('phase1', models.DecimalField(blank=True, decimal_places=4, max_digits=100, null=True, verbose_name='Phase L1')),
                ('phase2', models.DecimalField(blank=True, decimal_places=4, max_digits=100, null=True, verbose_name='Phase L2')),
                ('phase1_3storm', models.DecimalField(blank=True, decimal_places=4, max_digits=100, null=True, verbose_name='Phase L1-3 together. Storm [A]')),
                ('phase1_3Spannung', models.DecimalField(blank=True, decimal_places=4, max_digits=100, null=True, verbose_name='Phase L1-3 together. Spannung [V]')),
                ('uhrzeit1', models.CharField(blank=True, max_length=20, verbose_name='Time1')),
                ('strom1', models.CharField(blank=True, max_length=20, verbose_name='Current1')),
                ('spannung1', models.CharField(blank=True, max_length=20, verbose_name='Voltage1')),
                ('uhrzeit2', models.CharField(blank=True, max_length=20, verbose_name='Time2')),
                ('strom2', models.CharField(blank=True, max_length=20, verbose_name='Current2')),
                ('spannung2', models.CharField(blank=True, max_length=20, verbose_name='Voltage2')),
                ('uhrzeit3', models.CharField(blank=True, max_length=20, verbose_name='Time3')),
                ('strom3', models.CharField(blank=True, max_length=20, verbose_name='Current3')),
                ('spannung3', models.CharField(blank=True, max_length=20, verbose_name='Voltage3')),
                ('uhrzeit4', models.CharField(blank=True, max_length=20, verbose_name='Time4')),
                ('strom4', models.CharField(blank=True, max_length=20, verbose_name='Current4')),
                ('spannung4', models.CharField(blank=True, max_length=20, verbose_name='Voltage4')),
                ('uhrzeit5', models.CharField(blank=True, max_length=20, verbose_name='Time5')),
                ('strom5', models.CharField(blank=True, max_length=20, verbose_name='Current5')),
                ('spannung5', models.CharField(blank=True, max_length=20, verbose_name='Voltage5')),
                ('uhrzeit6', models.CharField(blank=True, max_length=20, verbose_name='Time6')),
                ('strom6', models.CharField(blank=True, max_length=20, verbose_name='Current6')),
                ('spannung6', models.CharField(blank=True, max_length=20, verbose_name='Voltage6')),
                ('Strom_A_45Hz', models.CharField(blank=True, max_length=20, verbose_name='Current 45Hz')),
                ('Spannung_V_45Hz', models.CharField(blank=True, max_length=20, verbose_name='Voltage 45Hz')),
                ('Strom_A_58Hz', models.CharField(blank=True, max_length=20, verbose_name='Current 58Hz')),
                ('Spannung_V_58Hz', models.CharField(blank=True, max_length=20, verbose_name='Voltage 58Hz')),
                ('Strom_A_65Hz', models.CharField(blank=True, max_length=20, verbose_name='Current 65Hz')),
                ('Spannung_V_65Hz', models.CharField(blank=True, max_length=20, verbose_name='Voltage 65Hz')),
            ],
        ),
    ]
