# Generated by Django 3.1 on 2021-04-18 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurements', '0003_measurements_kommentar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurements',
            name='phase1',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Phase L1'),
        ),
        migrations.AlterField(
            model_name='measurements',
            name='phase1_3Spannung',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Phase L1-3 together. Spannung [V]'),
        ),
        migrations.AlterField(
            model_name='measurements',
            name='phase1_3storm',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Phase L1-3 together. Storm [A]'),
        ),
        migrations.AlterField(
            model_name='measurements',
            name='phase2',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Phase L2'),
        ),
    ]
