# Generated by Django 3.1 on 2021-04-15 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('voltage_profile', '0001_initial'),
        ('measurements', '0001_initial'),
        ('touch_voltage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visualisation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measurement', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='measurement', to='measurements.measurements')),
                ('results_touch_voltage', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visualisationTV', to='touch_voltage.touchvoltage')),
                ('results_voltage_profile', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visualisationVP', to='voltage_profile.voltageprofile')),
            ],
        ),
    ]
