# Generated by Django 3.1 on 2021-04-19 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
        ('visualisations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visualisation',
            name='results_touch_voltage',
        ),
        migrations.AddField(
            model_name='visualisation',
            name='results_map',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visualisationTVMap', to='map.map'),
        ),
    ]
