# Generated by Django 3.1 on 2021-04-21 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualisations', '0002_auto_20210419_1752'),
    ]

    operations = [
        migrations.AddField(
            model_name='visualisation',
            name='project_identifier',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
